services:
  app:
    build: .
    container_name: distributed-rate-limiter-app
    ports:
      - "50051:50051"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/ratelimiter
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    container_name: distributed-rate-limiter-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ratelimiter
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro,Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ratelimiter"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  redis: 
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5