services:
  postgres:
    image: postgres:15-alpine
    container_name: distributed-rate-limiter-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ratelimiter
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro,Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ratelimiter"]
      interval: 5s
      timeout: 5s
      retries: 5
