// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               v5.29.6
// source: ratelimit.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Duration } from "./google/protobuf/duration";

export const protobufPackage = "ratelimit.v1";

export interface AcquireRequest {
  /**
   * logical_key identifies the resource (e.g., "user:123").
   * Max length: 256 bytes.
   */
  logicalKey: string;
  /**
   * cost is the number of tokens to consume.
   * Must be > 0.
   */
  cost: number;
  /**
   * request_id is a UUIDv4 client-generated token for idempotency.
   * REQUIRED. Requests without this will be rejected.
   */
  requestId: string;
}

export interface AcquireResponse {
  verdict: AcquireResponse_Verdict;
  /** remaining represents the accurate token balance at the time of commit. */
  remaining: number;
  /**
   * retry_after indicates when the client should retry if DENIED.
   * 0 if ALLOWED.
   */
  retryAfter:
    | Duration
    | undefined;
  /** metadata for debugging (optional) */
  metadata: { [key: string]: string };
}

export enum AcquireResponse_Verdict {
  VERDICT_UNSPECIFIED = 0,
  /**
   * ALLOWED - ALLOWED: Tokens were successfully consumed.
   * State is durable.
   */
  ALLOWED = 1,
  /**
   * DENIED - DENIED: Insufficient tokens.
   * State (refill) was committed, but consumption failed.
   */
  DENIED = 2,
  UNRECOGNIZED = -1,
}

export function acquireResponse_VerdictFromJSON(object: any): AcquireResponse_Verdict {
  switch (object) {
    case 0:
    case "VERDICT_UNSPECIFIED":
      return AcquireResponse_Verdict.VERDICT_UNSPECIFIED;
    case 1:
    case "ALLOWED":
      return AcquireResponse_Verdict.ALLOWED;
    case 2:
    case "DENIED":
      return AcquireResponse_Verdict.DENIED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AcquireResponse_Verdict.UNRECOGNIZED;
  }
}

export function acquireResponse_VerdictToJSON(object: AcquireResponse_Verdict): string {
  switch (object) {
    case AcquireResponse_Verdict.VERDICT_UNSPECIFIED:
      return "VERDICT_UNSPECIFIED";
    case AcquireResponse_Verdict.ALLOWED:
      return "ALLOWED";
    case AcquireResponse_Verdict.DENIED:
      return "DENIED";
    case AcquireResponse_Verdict.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface AcquireResponse_MetadataEntry {
  key: string;
  value: string;
}

export interface HealthCheckRequest {
}

export interface HealthCheckResponse {
  status: string;
  uptime: number;
  backend: string;
}

function createBaseAcquireRequest(): AcquireRequest {
  return { logicalKey: "", cost: 0, requestId: "" };
}

export const AcquireRequest: MessageFns<AcquireRequest> = {
  encode(message: AcquireRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.logicalKey !== "") {
      writer.uint32(10).string(message.logicalKey);
    }
    if (message.cost !== 0) {
      writer.uint32(16).uint32(message.cost);
    }
    if (message.requestId !== "") {
      writer.uint32(26).string(message.requestId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AcquireRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAcquireRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.logicalKey = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.cost = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AcquireRequest {
    return {
      logicalKey: isSet(object.logicalKey)
        ? globalThis.String(object.logicalKey)
        : isSet(object.logical_key)
        ? globalThis.String(object.logical_key)
        : "",
      cost: isSet(object.cost) ? globalThis.Number(object.cost) : 0,
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
    };
  },

  toJSON(message: AcquireRequest): unknown {
    const obj: any = {};
    if (message.logicalKey !== "") {
      obj.logicalKey = message.logicalKey;
    }
    if (message.cost !== 0) {
      obj.cost = Math.round(message.cost);
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AcquireRequest>, I>>(base?: I): AcquireRequest {
    return AcquireRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AcquireRequest>, I>>(object: I): AcquireRequest {
    const message = createBaseAcquireRequest();
    message.logicalKey = object.logicalKey ?? "";
    message.cost = object.cost ?? 0;
    message.requestId = object.requestId ?? "";
    return message;
  },
};

function createBaseAcquireResponse(): AcquireResponse {
  return { verdict: 0, remaining: 0, retryAfter: undefined, metadata: {} };
}

export const AcquireResponse: MessageFns<AcquireResponse> = {
  encode(message: AcquireResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.verdict !== 0) {
      writer.uint32(8).int32(message.verdict);
    }
    if (message.remaining !== 0) {
      writer.uint32(17).double(message.remaining);
    }
    if (message.retryAfter !== undefined) {
      Duration.encode(message.retryAfter, writer.uint32(26).fork()).join();
    }
    globalThis.Object.entries(message.metadata).forEach(([key, value]: [string, string]) => {
      AcquireResponse_MetadataEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AcquireResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAcquireResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.verdict = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.remaining = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.retryAfter = Duration.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = AcquireResponse_MetadataEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.metadata[entry4.key] = entry4.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AcquireResponse {
    return {
      verdict: isSet(object.verdict) ? acquireResponse_VerdictFromJSON(object.verdict) : 0,
      remaining: isSet(object.remaining) ? globalThis.Number(object.remaining) : 0,
      retryAfter: isSet(object.retryAfter)
        ? Duration.fromJSON(object.retryAfter)
        : isSet(object.retry_after)
        ? Duration.fromJSON(object.retry_after)
        : undefined,
      metadata: isObject(object.metadata)
        ? (globalThis.Object.entries(object.metadata) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: AcquireResponse): unknown {
    const obj: any = {};
    if (message.verdict !== 0) {
      obj.verdict = acquireResponse_VerdictToJSON(message.verdict);
    }
    if (message.remaining !== 0) {
      obj.remaining = message.remaining;
    }
    if (message.retryAfter !== undefined) {
      obj.retryAfter = Duration.toJSON(message.retryAfter);
    }
    if (message.metadata) {
      const entries = globalThis.Object.entries(message.metadata) as [string, string][];
      if (entries.length > 0) {
        obj.metadata = {};
        entries.forEach(([k, v]) => {
          obj.metadata[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AcquireResponse>, I>>(base?: I): AcquireResponse {
    return AcquireResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AcquireResponse>, I>>(object: I): AcquireResponse {
    const message = createBaseAcquireResponse();
    message.verdict = object.verdict ?? 0;
    message.remaining = object.remaining ?? 0;
    message.retryAfter = (object.retryAfter !== undefined && object.retryAfter !== null)
      ? Duration.fromPartial(object.retryAfter)
      : undefined;
    message.metadata = (globalThis.Object.entries(object.metadata ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseAcquireResponse_MetadataEntry(): AcquireResponse_MetadataEntry {
  return { key: "", value: "" };
}

export const AcquireResponse_MetadataEntry: MessageFns<AcquireResponse_MetadataEntry> = {
  encode(message: AcquireResponse_MetadataEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AcquireResponse_MetadataEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAcquireResponse_MetadataEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AcquireResponse_MetadataEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: AcquireResponse_MetadataEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AcquireResponse_MetadataEntry>, I>>(base?: I): AcquireResponse_MetadataEntry {
    return AcquireResponse_MetadataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AcquireResponse_MetadataEntry>, I>>(
    object: I,
  ): AcquireResponse_MetadataEntry {
    const message = createBaseAcquireResponse_MetadataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseHealthCheckRequest(): HealthCheckRequest {
  return {};
}

export const HealthCheckRequest: MessageFns<HealthCheckRequest> = {
  encode(_: HealthCheckRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HealthCheckRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHealthCheckRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): HealthCheckRequest {
    return {};
  },

  toJSON(_: HealthCheckRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<HealthCheckRequest>, I>>(base?: I): HealthCheckRequest {
    return HealthCheckRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HealthCheckRequest>, I>>(_: I): HealthCheckRequest {
    const message = createBaseHealthCheckRequest();
    return message;
  },
};

function createBaseHealthCheckResponse(): HealthCheckResponse {
  return { status: "", uptime: 0, backend: "" };
}

export const HealthCheckResponse: MessageFns<HealthCheckResponse> = {
  encode(message: HealthCheckResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.uptime !== 0) {
      writer.uint32(16).int64(message.uptime);
    }
    if (message.backend !== "") {
      writer.uint32(26).string(message.backend);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HealthCheckResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHealthCheckResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.uptime = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.backend = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HealthCheckResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      uptime: isSet(object.uptime) ? globalThis.Number(object.uptime) : 0,
      backend: isSet(object.backend) ? globalThis.String(object.backend) : "",
    };
  },

  toJSON(message: HealthCheckResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.uptime !== 0) {
      obj.uptime = Math.round(message.uptime);
    }
    if (message.backend !== "") {
      obj.backend = message.backend;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HealthCheckResponse>, I>>(base?: I): HealthCheckResponse {
    return HealthCheckResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HealthCheckResponse>, I>>(object: I): HealthCheckResponse {
    const message = createBaseHealthCheckResponse();
    message.status = object.status ?? "";
    message.uptime = object.uptime ?? 0;
    message.backend = object.backend ?? "";
    return message;
  },
};

export type RateLimiterService = typeof RateLimiterService;
export const RateLimiterService = {
  /**
   * Acquire attempts to consume `cost` tokens from the bucket `key`.
   *
   * Consistency:
   * - Returns only after the transaction is COMMITTED to the DB.
   * - If the deadline expires, the client MUST assume the result is UNKNOWN (but treated as Denied).
   */
  acquire: {
    path: "/ratelimit.v1.RateLimiter/Acquire",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: AcquireRequest): Buffer => Buffer.from(AcquireRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): AcquireRequest => AcquireRequest.decode(value),
    responseSerialize: (value: AcquireResponse): Buffer => Buffer.from(AcquireResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): AcquireResponse => AcquireResponse.decode(value),
  },
  healthCheck: {
    path: "/ratelimit.v1.RateLimiter/HealthCheck",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: HealthCheckRequest): Buffer => Buffer.from(HealthCheckRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): HealthCheckRequest => HealthCheckRequest.decode(value),
    responseSerialize: (value: HealthCheckResponse): Buffer => Buffer.from(HealthCheckResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): HealthCheckResponse => HealthCheckResponse.decode(value),
  },
} as const;

export interface RateLimiterServer extends UntypedServiceImplementation {
  /**
   * Acquire attempts to consume `cost` tokens from the bucket `key`.
   *
   * Consistency:
   * - Returns only after the transaction is COMMITTED to the DB.
   * - If the deadline expires, the client MUST assume the result is UNKNOWN (but treated as Denied).
   */
  acquire: handleUnaryCall<AcquireRequest, AcquireResponse>;
  healthCheck: handleUnaryCall<HealthCheckRequest, HealthCheckResponse>;
}

export interface RateLimiterClient extends Client {
  /**
   * Acquire attempts to consume `cost` tokens from the bucket `key`.
   *
   * Consistency:
   * - Returns only after the transaction is COMMITTED to the DB.
   * - If the deadline expires, the client MUST assume the result is UNKNOWN (but treated as Denied).
   */
  acquire(
    request: AcquireRequest,
    callback: (error: ServiceError | null, response: AcquireResponse) => void,
  ): ClientUnaryCall;
  acquire(
    request: AcquireRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: AcquireResponse) => void,
  ): ClientUnaryCall;
  acquire(
    request: AcquireRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: AcquireResponse) => void,
  ): ClientUnaryCall;
  healthCheck(
    request: HealthCheckRequest,
    callback: (error: ServiceError | null, response: HealthCheckResponse) => void,
  ): ClientUnaryCall;
  healthCheck(
    request: HealthCheckRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: HealthCheckResponse) => void,
  ): ClientUnaryCall;
  healthCheck(
    request: HealthCheckRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: HealthCheckResponse) => void,
  ): ClientUnaryCall;
}

export const RateLimiterClient = makeGenericClientConstructor(
  RateLimiterService,
  "ratelimit.v1.RateLimiter",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): RateLimiterClient;
  service: typeof RateLimiterService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
